version: "3.7"
services:
  app:
    build:
      args:
        user: sten
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: stenup
    container_name: stenup-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - stenup
    depends_on:
      - db
      - nginx
      - phpmyadmin

  db:
    image: mysql:5.7
    container_name: stenup-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      # Remain DB even when "docker-compose down"
      - dbdata:/var/lib/mysql
      # Execute docker-compose/mysql/db_init.sql when build image with "docker-compose build --no-cache"
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - stenup

  nginx:
    image: nginx:alpine
    container_name: stenup-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - stenup

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    container_name: stenup-phpmyadmin
    ports:
      - "8080:80"
#    volumes:
#      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    networks:
      - stenup
    depends_on:
      - db

networks:
  stenup:
    driver: bridge

volumes:
  dbdata:
    driver: local
