version: "3.7"
services:
  app:
    build:
      args:
        user: sten
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: stenup
    container_name: stenup-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - stenup

  db:
    image: mysql:5.7
    container_name: stenup-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - stenup

  nginx:
    image: nginx:alpine
    container_name: stenup-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - stenup

networks:
  stenup:
    driver: bridge
